#!/bin/sh
#
# User's .xinitrc file

# Merge custom X resources
xrdb -merge "${HOME}/.Xresources"

# Start a terminal emulator in the background
urxvt -T Terminal && tmux

# Start the window manager
exec i3

# treat CAPS LOCK like esc
/usr/bin/setxkbmap -option caps:escape
