version: '2.1'
orbs:
  node: circleci/node@7.1.0
jobs:
  update-version:
    docker:
      - image: 'cimg/node:current'
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm install semantic-release/npm @semantic-release/changelog @semantic-release/git
      - run: npx semantic-release --branches main
workflows:
  versioning:
    jobs:
      - update-version:
          context:
            - circleci
