version: 2.1

workflows:
  dotfile-versioning:
    jobs:
      - versioning:
          filters:
            branches:
              only: main
          context:
              circleci
jobs:
  versioning:
    docker:
      - image: circleci/node:17.6.0
    steps:
      - checkout
      - run: npm install semantic-release @semantic-release/changelog @semantic-release/git
      - run: npx semantic-release --branches main
