# Load .profile to set environment, etc
if [ -f "HOME/.profile" ]; then
    . "$HOME/.profile"
fi
# include .bashrc if it exists
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
export BASH_SILENCE_DEPRECATION_WARNING=1
