#!/bin/bash
# hide aws credentials in one place

export AWS_CONFIG_FILE=~/.aws/config

filename="$HOME/.aws/credentials"
while read -r line
do
    sedline="$line"
    export "$sedline" | sed -n '/aws/p'
done < "$filename"

